create table config(Name varchar(120),last_extract datetime) 
create table artist_STG(ArtistId int primary key,Name varchar(120),created_date datetime)
create table genre_STG(GenreId int primary key,Name varchar(120),created_date datetime)
create table tracks_STG(TrackId int,Track_invoiceline int,GenreId int,AlbumId int,ArtistId int,customerId int,unitprice int)
insert into config values ('customer','1950/1/1'),('genre','1950/1/1'),('artist','1950/1/1'),('tracks','1950/1/1')